services:
  directus-dev:
    profiles: [dev]
    build:
      context: ./directus
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      directus-db-dev:
        condition: service_healthy
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus-config:/directus/directus-config
    restart: unless-stopped
    environment:
      PUBLIC_URL: ${DIRECTUS_URL}
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
      SECRET: ${DIRECTUS_SECRET}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      ADMIN_TOKEN: ${DIRECTUS_ADMIN_TOKEN}
      DB_CLIENT: "pg"
      DB_HOST: "directus-db-dev"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: ${DIRECTUS_DB_PASSWORD}
      COLLECTIVO_API_URL: ${COLLECTIVO_API_URL}
      COLLECTIVO_API_TOKEN: ${COLLECTIVO_API_TOKEN}
      FLOWS_ENV_ALLOW_LIST: "PUBLIC_URL,COLLECTIVO_API_URL,COLLECTIVO_API_TOKEN"

  directus-db-dev:
    profiles: [dev]
    image: postgis/postgis:16-3.4-alpine
    volumes:
      - directus-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: "directus"
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: ${DIRECTUS_DB_PASSWORD}

  keycloak-db:
    image: postgres:14-alpine
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}

volumes:
  directus-db-data:
  keycloak-db-data:
